---
title: "ml_final_proj_insulin_diabetes"
author: "Yue Wu"
date: "December 6, 2018"
output: html_document
---

```{r,cache=TRUE,message=FALSE,warnings=FALSE}
### Load helper packages ###
loadlibs = function(libs) {
  for(lib in libs) {
    class(lib)
    if(!do.call(require,as.list(lib))) {install.packages(lib)}
    do.call(require,as.list(lib))
  }
}
libs = c("tidyr","magrittr","purrr","dplyr","stringr","readr","data.table",
         "keras","ggplot2","imager","pROC","VIM","mice","RWeka","caret")
loadlibs(libs)
options(warn = -1)
```


```{r}
#read files
setwd("C:/Users/wuyue/Desktop/CMU/ML-Pipeline/Final")
fileDirectory = "C:/Users/wuyue/Desktop/CMU/ML-Pipeline/Final/dataset_diabetes"

diabetic_data = read.csv(paste0(fileDirectory,"/diabetic_data.csv",sep=""),na.strings = c("?","Unknown/Invalid"))
```

```{r,cache=TRUE}
#missing pattern
aggr(diabetic_data, col = c('grey28','darkorange2'), numbers=TRUE, sortVars=TRUE, 
                  labels=names(diabetic_data), cex.axis=0.7, gap=3, 
                  ylab=c("Histogram of missing data", "Pattern"))
#exclude variables with too much missing data(>=40%), irrelavent variables and unreasonable indicators
diabetic_data=diabetic_data%>%select(-weight,-medical_specialty,-payer_code,-encounter_id,-patient_nbr,-admission_source_id, -change)
#remove entry with missing diagnosis and gender
diabetic_data=diabetic_data[-which(is.na(diabetic_data$diag)),]
diabetic_data=diabetic_data[-which(is.na(diabetic_data$gender)),]

#transform outcomes flag
diabetic_data$readmitted=ifelse(diabetic_data$readmitted=="<30",TRUE,FALSE)

#transform categorical variables
diabetic_data=diabetic_data %>% mutate(admission_type_id=admission_type_id %>% as.factor()) %>% mutate(discharge_disposition_id=discharge_disposition_id %>% as.factor())
  
#summary statistics
summary(diabetic_data)

#remove imbalance variables(only have almost one value)
diabetic_data=diabetic_data %>% select(-examide, -citoglipton,-acetohexamide,-troglitazone,-tolazamide,-glimepiride.pioglitazone, -metformin.rosiglitazone,-metformin.pioglitazone，-chlorpropamide,-tolbutamide,-miglitol,-glyburide.metformin,-glipizide.metformin,-acarbose)

#summary statistics of final data
summary(diabetic_data)

#filter infrequent diagnosis
diag_count=diabetic_data %>% dplyr::group_by(diag) %>% dplyr::summarise(count=n()) %>% as.data.frame()
diag_count_top=diag_count[which(diag_count$count>50),]
diabetic_data=diabetic_data %>% filter(diag %in% diag_count_top$diag)
diabetic_data$diag=droplevels(diabetic_data$diag)

#It is code for observing relationships between each two variables
# panel.cor <- function(x, y, digits = 2, prefix = "", cex.cor, ...)
# {
#     usr <- par("usr"); on.exit(par(usr))
#     par(usr = c(0, 1, 0, 1))
#     r <- abs(cor(x, y))
#     txt <- format(c(r, 0.123456789), digits = digits)[1]
#     txt <- paste0(prefix, txt)
#     if(missing(cex.cor)) cex.cor <- 0.8/strwidth(txt)
#     text(0.5, 0.5, txt, cex = pmax(1, cex.cor * r))
# }
# 
# pairs(diabetic_data, lower.panel = panel.cor)

#split into test/train data by 3:7
diabetic_data=diabetic_data[sample(1:nrow(diabetic_data)),]
traindata = diabetic_data[1:floor(nrow(diabetic_data)*0.7),]
testdata = diabetic_data[-(1:floor(nrow(diabetic_data)*0.7)),]

#impute missing data in train set
traindata.imputed = mice(traindata %>% 
              select(-readmitted) %>% 
              mutate_if(is.character, as.factor), m=1, maxit=5,  nnet.MaxNWts = 10000) 
#just use the first imputed set as the dataset is too large
train.imputed = complete(traindata.imputed) %>% as_tibble()
traindata.imputed = data.frame(result = traindata$readmitted%>%as.factor())%>%
                    bind_cols(train.imputed) %>% as_tibble()

#impute missing data in test set
testdata.imputed = mice(testdata %>% 
              select(-readmitted) %>% 
              mutate_if(is.character, as.factor), m=1, maxit=5, nnet.MaxNWts=10000)
#just use the first imputed set for convenience
test.imputed = complete(testdata.imputed) %>% as_tibble()
testdata.imputed = data.frame(result = testdata$readmitted%>%as.factor())%>%
                    bind_cols(test.imputed) %>% as_tibble()
```

```{r}
# logistic regression
lr.all = glm(result==TRUE ~ ., data = traindata.imputed, family = binomial("logit"))
lr.no.insulin = glm(result==TRUE ~ ., data = traindata.imputed %>% select(-insulin), family = binomial("logit"))

#draw ROC graph
lr.all.predict = lr.all %>% predict(testdata.imputed, type="response")
lr.all.rocdata=data.frame(pred = lr.all.predict, truth=testdata.imputed$result)
lr.no.insulin.predict = lr.no.insulin %>% predict(testdata.imputed%>% select(-insulin), type="response")
lr.no.insulin.rocdata=data.frame(pred = lr.no.insulin.predict, truth=testdata.imputed$result)
lr.all.roc <- roc(lr.all.rocdata$truth,lr.all.rocdata$pred)
plot(lr.all.roc, col="red")
par(new=TRUE)
lr.no.insulin.roc <- roc(lr.no.insulin.rocdata$truth,lr.no.insulin.rocdata$pred)
plot(lr.no.insulin.roc, col="blue")
legend("topright",legend=c(paste0("LR_All","(",round(lr.all.roc$auc,4),")"),                           paste0("LR_no_Insulin","(",round(lr.no.insulin.roc$auc,4),")")),pch=20, pt.cex=2)

#calculate significance level and coefficient
lr.summary=lr %>% summary() %>% coef() 
lr.summary["insulinSteady","Pr(>|z|)"]
lr.summary["insulinUp","Pr(>|z|)"]
lr.summary["insulinNo","Pr(>|z|)"]
lr.summary["insulinSteady","Estimate"] %>% exp()-1

```
